// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iebzlhwcyiptxsutugep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllYnpsaHdjeWlwdHhzdXR1Z2VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0NjQxNDEsImV4cCI6MjA1NzA0MDE0MX0.Q-sKC8zCwIp-Qmzr1Y7V1caueX22riqVJnZ1GjqLCH8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);